#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define BULLET_COLLISION_BITMASK	1
#define ENEMY_COLLISION_BITMASK		2
#define PLAYER_COLLISION_BITMASK	3
#define WORLD_COLLISION_BITMASK		4

#define BULLET_TAG					1
#define	ENEMY_TAG					2

#define PISTOL_FIRE_RATE			0.5
#define MACHINEGUN_FIRE_RATE		0.1
#define SHOTGUN_FIRE_RATE			1.0

#endif // __DEFINITIONS_H__